### PR TITLE
Fix 403

### PR DESCRIPTION
**Pull request by davipatricio**
**Please describe the changes this PR makes and why it should be merged:** module changed to youtube-infofix, so 403 error won't happen anymore

**Status**

- [x] Code changes have been tested against the Discord API and the discord.js wrapper, or there are no code changes

**Semantic versioning classification:**

- [ ] This PR changes DBM's interface (methods or parameters added to default methods)
- [ ] This PR **only** includes non-code changes, like changes to documentation, README, etc.

### CODE REVIEW

**Comment by davipatricio** [comment]
module changed to youtube-infofix, so 403 error won't happen anymore

**Comment by TheMonDon** [comment]
Can you make the github repository public so we can see what you actually changed to find out if it works? Thanks.

**Comment by davipatricio** [comment]
https://cdn.jsdelivr.net/npm/youtube-infofix@1.3.7/

**Comment by Almeeida** [comment]
We'll be going with this one instead, thank you anyway. https://github.com/dbm-network/mods/pull/468

**Pull request closed without merging**
