### PR TITLE
Transcript_MOD

### PR DESCRIPTION
**Pull request by LFDPhoenix1411**
**Please describe the changes this PR makes and why it should be merged:**
Requires  #952 approval before mod can be added.

This PR adds the Transcript_MOD, this allows Users to make a Transcript from a Channel that looks like this : 

IMUGUR IMAGE

The Transcript Mods outputs it as a String that can used to save it in a file or use in other ways

also a example command : https://pastebin.com/QzV6hb6J

Known Problem it needs to use discord-html-transcripts@2.6.1, but I don't know how to force installing this version and not the latest

**Status**

- [x] Code changes have been tested against the Discord API and the discord.js wrapper, or there are no code changes
- [x] Documentation has been added/modified, or there is nothing to change (docs/mods.json)

**Semantic versioning classification:**

- [ ] This PR changes DBM's interface (methods or parameters added to default methods)
- [ ] This PR **only** includes non-code changes, like changes to documentation, README, etc.

### CODE REVIEW

**Comment by TheMonDon** [comment]
Why does it use discord-html-transcripts@2.6.1?

**Comment by LFDPhoenix1411** [comment]
i need 2.6.1 because the higher version is only for discord v14
https://www.npmjs.com/package/discord-html-transcripts <-- Latest
https://www.npmjs.com/package/discord-html-transcripts/v/2.6.1 <-- 2.6.1

**Comment by TheMonDon** [comment]
> i need 2.6.1 because the higher version is only for discord v14 https://www.npmjs.com/package/discord-html-transcripts <-- Latest https://www.npmjs.com/package/discord-html-transcripts/v/2.6.1 <-- 2.6.1

Alright that makes sense, does the package have a version property, maybe throw an error if version is not 2.6.1? 

Also for this instance remove the automated module installer because that will always install the latest version, require the module manually and maybe place a comment inside the mod to use 2.6.1?

**Comment by LFDPhoenix1411** [comment]
> > i need 2.6.1 because the higher version is only for discord v14 https://www.npmjs.com/package/discord-html-transcripts <-- Latest https://www.npmjs.com/package/discord-html-transcripts/v/2.6.1 <-- 2.6.1
> 
> Alright that makes sense, does the package have a version property, maybe throw an error if version is not 2.6.1?
> 
> Also for this instance remove the automated module installer because that will always install the latest version, require the module manually and maybe place a comment inside the mod to use 2.6.1?

i will try it and also make a comment

**Comment by LFDPhoenix1411** [comment]
```javascript
const discordTranscripts = require('discord-html-transcripts'); // USE VERSION 2.6.1

const dtVersion = require('../package.json').dependencies['discord-html-transcripts']; // Get Version

if (dtVersion === '^2.6.1') {
  //CODE HERE
} else {
  console.log(`Current Version ${dtVersion}`);
  console.log('Needed Version ^2.6.1');
  console.log('Use npm i discord-html-transcripts@2.6.1 to install the right version');
  process.exit(1);
}
```
did you mean like this?

**Review by TheMonDon — APPROVED** [review]

**Pull request merged**
