### PR TITLE
Canvas jimp compatibility

### PR DESCRIPTION
**Pull request by LeonZ2019**
allow use canvas mod and default image action together

**Please describe the changes this PR makes and why it should be merged:**

**Status**

- [x] Code changes have been tested against the Discord API and the discord.js wrapper, or there are no code changes
- [ ] Documentation has been added/modified, or there is nothing to change (docs/mods.json)

**Semantic versioning classification:**

- [ ] This PR changes DBM's interface (methods or parameters added to default methods)
- [ ] This PR **only** includes non-code changes, like changes to documentation, README, etc.

### CODE REVIEW

**Comment by Fisheiyy** [comment]
> allow use canvas mod and default image action together
> 
> **Please describe the changes this PR makes and why it should be merged:**
> 
> **Status**
> 
> * [x]  Code changes have been tested against the Discord API and the discord.js wrapper, or there are no code changes
> * [ ]  Documentation has been added/modified, or there is nothing to change (docs/mods.json)
> 
> **Semantic versioning classification:**
> 
> * [ ]  This PR changes DBM's interface (methods or parameters added to default methods)
> * [ ]  This PR **only** includes non-code changes, like changes to documentation, README, etc.

can you check the boxes of what you have done?

**Review by DetroitWhiskey136 — CHANGES_REQUESTED** [review]
find a way to have the deps installed locally instead of adding them in through the mod pack

**Comment by Fisheiyy** [comment]
honestly dont think at this point that the PR author is going to do anything

**Comment by TheMonDon** [comment]
> honestly dont think at this point that the PR author is going to do anything

@almeidx / @DetroitWhiskey136 I am agreeing here and think this can be closed if the PR owner isn't going to respond.

**Pull request closed without merging**
