### PR TITLE
Update global_data_MOD.js 

### PR DESCRIPTION
**Pull request by Phyrok**
**Please describe the changes this PR makes and why it should be merged:**
Outdated looks updated to look more appealing with the rest of the actions.

Removal of unnecessary code in **Check_Global_Data.js** as it DBM has a build in conditional input. 

| **Check_Global_Data.js** | **Control_Global_Data.js** | **Delete_Global_Data.js** | **Store_Global_Data.js** |
| :--- | :--- | :--- | :--- | 
| <details> <summary>Before</summary> image </details> | <details> <summary>Before</summary> image </details> | <details> <summary>Before</summary> image </details> | <details> <summary>Before</summary> image </details>
|<details> <summary>After</summary> image </details> | <details> <summary>After</summary> image </details> | <details> <summary>After</summary> image </details> | <details> <summary>After</summary> image </details>

**Status**

- [x] Code changes have been tested against the Discord API and the discord.js wrapper, or there are no code changes
- [ ] Documentation has been added/modified, or there is nothing to change (docs/mods.json)

**Semantic versioning classification:**

- [ ] This PR changes DBM's interface (methods or parameters added to default methods)
- [ ] This PR **only** includes non-code changes, like changes to documentation, README, etc.

### CODE REVIEW

**Comment by OneAndonlyFinbar** [comment]
please remove the documentation comments

**Comment by OneAndonlyFinbar** [comment]
or at least make them smaller

**Comment by Phyrok** [comment]
I added them because I copied them from the Default Actions, that way it was easier for me to understand what I was editing.

**Comment by Phyrok** [comment]
Are they causing issues?

**Comment by Phyrok** [comment]
From the "Checks" I can see there is something wrong, I will revert back to the old file and only adjust the visuals although that might make it harder to remove the "Value to Compare to" from the "Exist" Selection.

**Comment by OneAndonlyFinbar** [comment]
checks have nothing to do with changed contents, and for most part tell you exactly what to change

**Pull request closed without merging**
