### PR TITLE
Convert ISO8061 to Unix Timestamp

### PR DESCRIPTION
**Pull request by Robskan5300**
My first contribution to the DBM mods. You can convert iso8061 dates to unix timestamps with this 👍

### CODE REVIEW

**Comment by OneAndonlyFinbar** [comment]
did you mean to add `actions/add_commas_to_number_MOD.js` too?

**Comment by OneAndonlyFinbar** [comment]
If so, [this](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/toLocaleString) is probably a better approach

**Comment by Robskan5300** [comment]
Yeah, it was my intention to add that one too. Do I need to change it, or is it OK like this?

**Comment by OneAndonlyFinbar** [comment]
no its fine

**Review by OneAndonlyFinbar — APPROVED** [review]

**Pull request merged**
