### PR TITLE
Added get dominant color mod

### PR DESCRIPTION
**Pull request by ForceBlood**
Original author: Ena

### CODE REVIEW

**Comment by dcorvus** [comment]
Who is `Ena`? Have you made appropriate changes to this Modification?

**Comment by ForceBlood** [comment]
Ena is the original author. He/She deleted this mod from his GitHub so no one can download it anymore. I asked almeida if I can get it added in the mods repository and he said that it was ok to share it here.

**Comment by dcorvus** [comment]
Have you asked the original author if they want it to be re-uploaded.

**Comment by ForceBlood** [comment]
I couldn't ask them because their account is deleted.

**Comment by Almeeida** [comment]
Add an author property on the action object with their name, and add `_MOD` at the end of the file name, please.

**Pull request merged**
