### PR TITLE
We removed all of the edited default actions.

### PR DESCRIPTION
**Pull request by DetroitWhiskey136**
**Please describe the changes this PR makes and why it should be merged:**

As per my chat with SRD regarding how the network will be handling mods going forward. We decided it would be best for the network not to deal with default actions at all. In the event another major update happens, it will be less work for the group to update/maintain (not much less).

**Status**

- [ ] Code changes have been tested against the Discord API and the discord.js wrapper, or there are no code changes
- [ ] Documentation has been added/modified, or there is nothing to change (docs/mods.json)

**Semantic versioning classification:**

- [ ] This PR changes DBM's interface (methods or parameters added to default methods)
- [ ] This PR **only** includes non-code changes, like changes to documentation, README, etc.

### CODE REVIEW

**Review by OneAndonlyFinbar — COMMENTED** [review]
Instead of removing the run script mod consider renaming the mod to something like evaluate expression as the default run script action doesnt have built in syntax checking/highlighting.

**Comment by DetroitWhiskey136** [comment]
or ask srd to add syntax highlighting we don't need three run script actions.

**Comment by DetroitWhiskey136** [comment]
I did keep the other one for now but even that one will probably be removed

**Comment by DetroitWhiskey136** [comment]
alright just verified we don't have a install conflict with default actions I think this can proceed

**Review by almeidx — APPROVED** [review]

**Pull request merged**
