### PR TITLE
Minor Fixes

### PR DESCRIPTION
**Pull request by Fisheiyy**
**Please describe the changes this PR makes and why it should be merged:**
changes some file names to match the current website name (dbl -> topgg) also added under the json path section of store json from webapi that says "you do not need to add the x." as many people make that mistake when using json path finders
**Status**

- [x] Code changes have been tested against the Discord API and the discord.js wrapper, or there are no code changes
- [x] Documentation has been added/modified, or there is nothing to change (docs/mods.json)

**Semantic versioning classification:**

- [ ] This PR changes DBM's interface (methods or parameters added to default methods)
- [x] This PR **only** includes non-code changes, like changes to documentation, README, etc.

### CODE REVIEW

**Comment by DanTheComputerMan** [comment]
Please change
<input id="dblToken" class="round" type="text">
 to 
<input id="TopggToken" class="round" type="text">
since you changed the field name to TopggToken

**Comment by Fisheiyy** [comment]
ahh didnt see that

**Comment by shinobihaxor** [comment]
(node:6776) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'ids' of null
    at Object.action [as Sends Stats to Top.gg] (C:\Users\User\Desktop\WatchDog\actions\send_stats_to_dbl_MOD.js:44:72)

**Comment by noahalma** [comment]
I don't understand why you're messing with my mod. Also, it's still called Discord Bot List. `top.gg` is just the website name. It literally says `Discord Bot List` when you search it up, and the Discord server is called `Discord Bot List`.

**Comment by Fisheiyy** [comment]
> (node:6776) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'ids' of null
> at Object.action [as Sends Stats to Top.gg] (C:\Users\User\Desktop\WatchDog\actions\send_stats_to_dbl_MOD.js:44:72)

That is not the same mods i have commited unless you renaned them for some reason

**Comment by Fisheiyy** [comment]
> I don't understand why you're messing with my mod. Also, it's still called Discord Bot List. `top.gg` is just the website name. It literally says `Discord Bot List` when you search it up, and the Discord server is called `Discord Bot List`.

No need to attack me damn bro im just trying to make it easier to indentiftmy what does what topgg is more well known because its the sites name

**Comment by shinobihaxor** [comment]
> > (node:6776) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'ids' of null
> > at Object.action [as Sends Stats to Top.gg] (C:\Users\User\Desktop\WatchDog\actions\send_stats_to_dbl_MOD.js:44:72)
> 
> That is not the same mods i have commited unless you renaned them for some reason, if it is I will test it myself and fix anything i broke when I get home in ~2 hours

I copied your code and replaced with the current, but it doesn't work, I placed the right token 100% sure

**Comment by Fisheiyy** [comment]
> > > (node:6776) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'ids' of null
> > > at Object.action [as Sends Stats to Top.gg] (C:\Users\User\Desktop\WatchDog\actions\send_stats_to_dbl_MOD.js:44:72)
> > 
> > 
> > That is not the same mods i have commited unless you renaned them for some reason, if it is I will test it myself and fix anything i broke when I get home in ~2 hours
> 
> I copied your code and replaced with the current, but it doesn't work, I placed the right token 100% sure

okay well im home now and will try myself

**Comment by shinobihaxor** [comment]
No... its not the fault of the topgg token.

(node:7296) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'ids' of null
    at Object.action [as Sends Stats to Top.gg] (C:\Users\User\Desktop\WatchDog\actions\send_stats_to_topgg_MOD.js:44:72)

Its something with these lines

    const body = [
      { server_count: client.guilds.cache.size },
      { server_count: client.guilds.cache.size, shard_id: client.shard.ids[0], shard_count: client.shard.count }
    ][info]

idk what

**Comment by Fisheiyy** [comment]
> No... its not the fault of the topgg token.
> 
> (node:7296) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'ids' of null
> at Object.action [as Sends Stats to Top.gg] (C:\Users\User\Desktop\WatchDog\actions\send_stats_to_topgg_MOD.js:44:72)
> 
> Its something with these lines
> 
> ```
> const body = [
>   { server_count: client.guilds.cache.size },
>   { server_count: client.guilds.cache.size, shard_id: client.shard.ids[0], shard_count: client.shard.count }
> ][info]
> ```
> 
> idk what

Well I didnt touch any of that so i didnt break that

**Pull request closed without merging**
