### PR TITLE
Added Json controls and Canvas update

### PR DESCRIPTION
**Pull request by thekingofspace**
Added json_read_MOD.js this is useful for the next action

Added json_write_MOD.js this will be useful for data storage purposes, stuff like storing user data for games. Now this could be done using data or file controlling, but this I feel like is nice for readabillity, editing and other uses! With content nesting to it can help with storing other things!

added more shapes to canvas :)

**Status**

- [X] Code changes have been tested against the Discord API and the discord.js wrapper, or there are no code changes
- [X] Documentation has been added/modified, or there is nothing to change (docs/mods.json)

**Semantic versioning classification:**

- [ ] This PR changes DBM's interface (methods or parameters added to default methods)
- [ ] This PR **only** includes non-code changes, like changes to documentation, README, etc.

### CODE REVIEW

**Review by OneAndOnlyFinbar — CHANGES_REQUESTED** [review]
fix checks, then its good

**Comment by thekingofspace** [comment]
I think I got it lint was giving me trouble

**Comment by thekingofspace** [comment]
GOD I am gonna rip my hair out lint will just not work with me

**Comment by thekingofspace** [comment]
Solved it, turns out I forgot a few case returns, mb

**Review by OneAndOnlyFinbar — APPROVED** [review]

**Pull request merged**
