### PR TITLE
Fix invite_used_EVT.js

### PR DESCRIPTION
**Pull request by GoodOne120**
I fix this, because TheMonDon couldn't.

**Please describe the changes this PR makes and why it should be merged:**

**Status**

- [x] Code changes have been tested against the Discord API and the discord.js wrapper, or there are no code changes
- [X] Documentation has been added/modified, or there is nothing to change (docs/mods.json)

**Semantic versioning classification:**

- [ ] This PR changes DBM's interface (methods or parameters added to default methods)
- [ ] This PR **only** includes non-code changes, like changes to documentation, README, etc.

### CODE REVIEW

**Comment by TheMonDon** [comment]
Hi please fix all the prettier errors (npm run prettier:fix)

**Comment by GoodOne120** [comment]
> Hi please fix all the prettier errors (npm run prettier:fix)

Fixed bro 😎😎😎😎😎😎😎😎😎😎😎😎😎😎

**Review by TheMonDon — APPROVED** [review]
Good job, you did a GoodOne

**Comment by GoodOne120** [comment]
> Good job, you did a GoodOne

It was easy asf, I dont understand how you couldn't do this on your own

**Pull request merged**
