### PR TITLE
New | Check Parameters Mod

### PR DESCRIPTION
**Pull request by Giingu**
**Please describe the changes this PR makes and why it should be merged:**
Adds the >= and <= type of comparisons.

**Status**

- [x] Code changes have been tested against the Discord API and the discord.js wrapper, or there are no code changes

**Semantic versioning classification:**

- [x] This PR changes DBM's interface (methods or parameters added to default methods)

### CODE REVIEW

**Comment by shinobihaxor** [comment]
you made 10 eslint errors, multiple code errors and had the guts to give yourself the author title which is funny imo

**Comment by Giingu** [comment]
> you made 10 eslint errors, multiple code errors and had the guts to give yourself the author title which is funny imo

The errors come from how the original action was made (DBM Dev), the mod itself is working completely fine.

**Comment by Mikee9165** [comment]
`Check Parameters` is a default action and if I'm not wrong, default actions won't be modded anymore. You might want to suggest this change to SRD. :^)

**Comment by DetroitWhiskey136** [comment]
because this is a modded default action we can't add it to the repo.

**Pull request closed without merging**
