### PR TITLE
Minimize DBM Errors

### PR DESCRIPTION
**Pull request by Michael55555**
**Please describe the changes this PR makes and why it should be merged:**
- This pull request minimizes the information presented in error messages to provide DBM developers with just the information they need.
How it looked like before:
image
How it looks like now
image

**Status**

- [ ] Code changes have been tested against the Discord API and the discord.js wrapper, or there are no code changes
- [ ] Documentation has been added/modified, or there is nothing to change (docs/mods.json)

**Semantic versioning classification:**

- [x] This PR changes DBM's interface (methods or parameters added to default methods)
- [ ] This PR **only** includes non-code changes, like changes to documentation, README, etc.

### CODE REVIEW

**Comment by Michael55555** [comment]
Linter errors already failed before, the code I added have no errors. 😉

**Comment by DanTheComputerMan** [comment]
You modified the html for no reason, mismatching quotes there.
chrome_plUqaNLinV

You also have a load of unused variables.

**Comment by Michael55555** [comment]
I fixed the HTML error, unfortunately the "unused" variables are required for the eval call just a few lines later. 😦

**Comment by master3395** [comment]
Where it says `-> at Run Script`
Will it say what run script or what action it is in?

**Comment by Michael55555** [comment]
> Where it says `-> at Run Script`
> Will it say what run script or what action it is in?

Unfortunately not.

**Comment by Michael55555** [comment]
Closing this issue as it doesn't seem to relevant for DBM anymore.

**Pull request closed without merging**
