### PR TITLE
Fix Parse from Stored JSON

### PR DESCRIPTION
**Pull request by Adib23704**
**Please describe the changes this PR makes and why it should be merged:**
It removes the `["` and `"]` from the start and the end of the output value that was parsed from **Parse from Stored JSON** action without ruining any `"` or brackets inside the value.

**Status**

- [x] Code changes have been tested against the Discord API and the discord.js wrapper, or there are no code changes
- [x] Documentation has been added/modified, or there is nothing to change (docs/mods.json)

**Semantic versioning classification:**

- [ ] This PR changes DBM's interface (methods or parameters added to default methods)
- [ ] This PR **only** includes non-code changes, like changes to documentation, README, etc.

### CODE REVIEW

**Comment by Adib23704** [comment]
> I'll be able to test this later. But from what it looks does this just invalidate the JSON syntax to make it human readable? What you provided makes it look like it removes string syntax and brackets from arrays, which would break it. If so use list actions instead.

It will only remove the quote and bracket character from the starting and the end of the string. Which would preserve the actual arrays that's within the string.

**Comment by OneAndonlyFinbar** [comment]
So for example it would change ["item 1", "item 2"] into item 1, item 2?

**Comment by Adib23704** [comment]
> So for example it would change `["item 1", "item 2"]` into `item 1, item 2`?

When we store a value from a stored json, the value will return like this `["value"]`. We have to use then replace text action to remove that quote and the bracket symbol. That's what I did, we won't have to use the replace text as it will remove the very first `["` and the very last `"]` from the parsed value. The quote and brackets that are inside the value remain intact.

**Comment by OneAndonlyFinbar** [comment]
There are list actions for a reason

**Pull request closed without merging**
