### PR TITLE
Create and remove buttons in a message with Event.

### PR DESCRIPTION
**Pull request by GabrielMota1056**
Using the discord-buttons module, I created 2 actions and 1 event.

**Add button**
- You can specify the message to edit.
- You can save the button object.
- You can change button text and style.

**Remove button**
- You can specify the message to edit.
- You can specify the position of the button.

And finally an event to save the user and the message.

### CODE REVIEW

**Comment by Mindlesscargo** [comment]
This definitely is not passing through the linter

**Comment by shinobihaxor** [comment]
add_buton.js error

TypeError: message.edit is not a function

**Comment by shinobihaxor** [comment]
Few issues with this, writing a full detailed review as of now

Issue #1
`(node:13016) UnhandledPromiseRejectionWarning: DiscordAPIError: Cannot send an empty message`
Can be fixed in embeds only when the message content is added
image

However this is currently useless to use with embeds follow next issue

https://gyazo.com/84bf380c0766184eff163118996250cb

Its useless to try adding buttons to embeds, because it edits original embed content with MESSAGE content as seen in #1 issue   

Problem is in line 214 add_button.js
`message.edit(message.content, { buttons: buttons })`

This works great with a regular message but not with embeds. Overall a great mod, but this doesn't work with embeds.

**Comment by almeidx** [comment]
We appreciate the efforts you put into this, but since discord.js is approaching the v13 release date, which includes buttons along with other features, we will not be adopting this library.

**Pull request closed without merging**
