### PR TITLE
New mod Capitalize

### PR DESCRIPTION
**Pull request by YagizKCKN**
**Some variables have lowercase letters and we cant change them like the data coming from the apis with this action you can be able to change the letters**

**Status**

- [ ] Code changes have been tested against the Discord API and the discord.js wrapper, or there are no code changes

**Semantic versioning classification:**

- [ ] This PR changes DBM's interface (methods or parameters added to default methods)
- [ ] This PR **only** includes non-code changes, like changes to documentation, README, etc.

### CODE REVIEW

**Comment by YagizKCKN** [comment]
It just converts all words mine gives you opportunity of selection of letter and word

**Comment by ForceBlood** [comment]
I agree with Leonz. Meeting it with the controll variable action is a better idea.

**Comment by YagizKCKN** [comment]
I merged with control variable action and removed capitalize.js as you said

**Comment by Almeeida** [comment]
This was rolled-back since it was merged into master instead of beta.

**Pull request merged**
