### PR TITLE
Fix store invite info MOD

### PR DESCRIPTION
**Pull request by ForceBlood**
**Please describe the changes this PR makes and why it should be merged:**

**Status**

- [x] Code changes have been tested against the Discord API and the discord.js wrapper, or there are no code changes
- [x] Documentation has been added/modified, or there is nothing to change (docs/mods.json)

**Semantic versioning classification:**

- [ ] This PR changes DBM's interface (methods or parameters added to default methods)
- [ ] This PR **only** includes non-code changes, like changes to documentation, README, etc.

### CODE REVIEW

**Comment by ForceBlood** [comment]
Fixes #932

**Comment by OneAndonlyFinbar** [comment]
"lgtm" but danno doesnt trust me with authorizing prs :p

**Comment by ForceBlood** [comment]
Danno pls trust finbar, me too while at it :)

**Review by TheMonDon — APPROVED** [review]
Looks fine, have to get alm or danno to actually approve anything though.

**Comment by OneAndonlyFinbar** [comment]
I have permission to merge but not permission to merge..

**Review by almeidx — APPROVED** [review]

**Comment by deag69** [comment]
Thanks @ForceBlood, great work :)

**Comment by ForceBlood** [comment]
@deag69 You are welcome

**Pull request merged**
