### PR TITLE
Created Currency Converter (also i added CC to mods.json)

### PR DESCRIPTION
**Pull request by pKunnn**
**Please describe the changes this PR makes and why it should be merged:**
It adds a new action to DBM that might be useful for some persons
**Status**

- [x] Code changes have been tested against the Discord API and the discord.js wrapper, or there are no code changes
- [x] Documentation has been added/modified, or there is nothing to change (docs/mods.json)

**Semantic versioning classification:**

- [ ] This PR changes DBM's interface (methods or parameters added to default methods)
- [ ] This PR **only** includes non-code changes, like changes to documentation, README, etc.

imagem_2022-11-05_020205917
imagem_2022-11-05_020324651

### CODE REVIEW

**Comment by pKunnn** [comment]
imma run prettier asap when i get home

**Comment by pKunnn** [comment]
done

**Review by OneAndonlyFinbar — CHANGES_REQUESTED** [review]
Preferably exceptions should call the next action and then return, as to continue the command.

**Review by almeidx — CHANGES_REQUESTED** [review]
See https://github.com/dbm-network/mods/pull/915#pullrequestreview-1169446365

**Comment by TheMonDon** [comment]
Closing due to inactivity from author. Feel free to re-open with changes required.

**Pull request closed without merging**
